---
#
# https://github.com/theforeman/foreman-operations-collection
# https://github.com/theforeman/foreman-ansible-modules
#
- name: Foreman Installer Playbook here
  hosts: "{{ server_group }}"

  # Setting which collections will be used/loaded
  collections:
    - theforeman.foreman
    - theforeman.operations

  vars:
   # Foreman Information (Use "katello" in def_scanerio if you want content and product)
    sat_user: "admin"
    sat_pass: "redhat"
    sat_org: "SOPHON"
    def_scenario: "katello"

 
  tasks:
#    - name: checking some variables
#      ansible.builtin.debug:
#        var: ansible_facts

    # Some standard operations to disable firewall
    - name: Disabling and Stopping firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no

    # Adding a local entry
    - name: Adding the entry to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ inventory_hostname }} {{ ansible_facts['fqdn'] }} {{ ansible_facts['hostname'] }}"

    # Adding the puppet repo, required for the installation
    - name: Installing Puppet Repository
      yum:
        name: https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
        state: present
        disable_gpg_check: true # if gpg check creates problem

    # Installing the foreman repo
    - name: Installing Foreman Repository
      yum:
        name: https://yum.theforeman.org/releases/3.10/el8/x86_64/foreman-release.rpm
        state: present
        disable_gpg_check: true

    # Installing the katello
    - name: Installing the Katello Repository
      yum:
        name: https://yum.theforeman.org/katello/4.12/katello/el8/x86_64/katello-repos-latest.rpm
        state: present
        disable_gpg_check: true

    # Installing the module
    - name: Enable the katello:el8
      yum:
        name: '@katello:el8'
        state: present

    # Update the system
    - name: Update the system
      yum:
        name: "*"
        state: latest # very careful here, if it is written "present" it throws error

    # Installing the foreman-installer package
    - name: Installing Foreman Package
      yum:
        name: foreman-installer-katello
        state: present

    # Calling the installer in fact, using the collection
    - import_role:
        name: theforeman.operations.installer
      vars:
        foreman_installer_scenario: "{{ def_scenario }}"
        foreman_installer_options:
          - '--foreman-initial-organization "{{ sat_org }}"'
          - '--foreman-initial-admin-password {{ sat_pass }}'
